language: generic
sudo: required
services:
  - docker
matrix:
  include:
    # Linux Installation.
    - os: linux
      env:
        - MATRIX_EVAL="docker build --build-arg DISTRO=14.04 MATRIX_EVAL='echo Ok!' -t trusty_tahr ./misc"
        - TESTS="docker run -it misc_trusty_tahr_1 bash -c 'cd /code/gamera && py.test'"
    - os: linux
      env:
        - MATRIX_EVAL="docker build --build-arg DISTRO=12.04 MATRIX_EVAL='echo Ok!' -t precise_pangolin ./misc"
        - TESTS="docker run -it misc_precise_pangolin_1 bash -c 'cd /code/gamera && py.test'"
    # Mac Installation.
    - os: osx
      osx_image: xcode9.4
      env:
        - HOMEBREW_NO_AUTO_UPDATE=1
        - MATRIX_EVAL="brew install python@2 wxpython"
        - TESTS="py.test"
    - os: osx
      osx_image: xcode9.3
      env:
        - HOMEBREW_NO_AUTO_UPDATE=1
        - MATRIX_EVAL="yes | python -m pip uninstall pip && brew install python@2 wxpython && brew postinstall python"
        - TESTS="py.test"
    - os: osx
      osx_image: xcode9.2
      env:
        - HOMEBREW_NO_AUTO_UPDATE=1
        - MATRIX_EVAL="yes | python -m pip uninstall pip && brew install python@2 wxpython && brew postinstall python"
        - TESTS="py.test"
    - os: osx
      osx_image: xcode9.1
      env:
        - HOMEBREW_NO_AUTO_UPDATE=1
        - MATRIX_EVAL="yes | python -m pip uninstall pip && brew install python@2 wxpython && brew postinstall python"
        - TESTS="py.test"
    - os: osx
      osx_image: xcode9
      env:
        - HOMEBREW_NO_AUTO_UPDATE=1
        - MATRIX_EVAL="yes | python -m pip uninstall pip && brew install python@2 wxpython && brew postinstall python"
        - TESTS="py.test"
    - os: osx
      osx_image: xcode8.3
      env:
        - HOMEBREW_NO_AUTO_UPDATE=1
        - MATRIX_EVAL="yes | python -m pip uninstall pip && brew install python@2 wxpython && brew postinstall python"
        - TESTS="py.test"
    - os: osx
      osx_image: xcode8
      env:
        - HOMEBREW_NO_AUTO_UPDATE=1
        - MATRIX_EVAL="yes | python -m pip uninstall pip && brew install python@2 wxpython && brew postinstall python"
        - TESTS="py.test"
install:
  - sudo chmod +x ./misc/install.sh
  - sudo $MATRIX_EVAL ./misc/install.sh
script:
  - eval ${TESTS}
