language: generic
sudo: required
matrix:
  include:
    # Linux Installation.
    - os: linux
      env:
        - MATRIX_EVAL="sudo apt-get update && sudo apt-get install python-wxgtk2.8 python-pip"
    - os: linux
      env:
        - MATRIX_EVAL="sudo apt-get update && sudo apt-get install python-wxgtk2.8 python-pip"
    # Mac Installation.
    - os: osx
      osx_image: xcode9.4
      env:
        - HOMEBREW_NO_AUTO_UPDATE=1
        - MATRIX_EVAL="brew install python@2 wxpython"
    - os: osx
      osx_image: xcode9.3
      env:
        - HOMEBREW_NO_AUTO_UPDATE=1
        - MATRIX_EVAL="yes | sudo python -m pip uninstall pip && brew install python@2 wxpython && brew postinstall python"
    - os: osx
      osx_image: xcode9.2
      env:
        - HOMEBREW_NO_AUTO_UPDATE=1
        - MATRIX_EVAL="yes | sudo python -m pip uninstall pip && brew install python@2 wxpython && brew postinstall python"
    - os: osx
      osx_image: xcode9.1
      env:
        - HOMEBREW_NO_AUTO_UPDATE=1
        - MATRIX_EVAL="yes | sudo python -m pip uninstall pip && brew install python@2 wxpython && brew postinstall python"
    - os: osx
      osx_image: xcode9
      env:
        - HOMEBREW_NO_AUTO_UPDATE=1
        - MATRIX_EVAL="yes | sudo python -m pip uninstall pip && brew install python@2 wxpython && brew postinstall python"
    - os: osx
      osx_image: xcode8.3
      env:
        - HOMEBREW_NO_AUTO_UPDATE=1
        - MATRIX_EVAL="yes | sudo python -m pip uninstall pip && brew install python@2 wxpython && brew postinstall python"
    - os: osx
      osx_image: xcode8
      env:
        - HOMEBREW_NO_AUTO_UPDATE=1
        - MATRIX_EVAL="yes | sudo python -m pip uninstall pip && brew install python@2 wxpython && brew postinstall python"
before_install:
  - eval "${MATRIX_EVAL}"
  - pip install -U pip
  - pip install pytest docutils pygments
install:
  - python setup.py build
  - python setup.py install
script:
  - py.test
