language: generic
sudo: required
matrix:
  include:
    # Linux Installation.
    # - os: linux
    #   env:
    #     - MATRIX="docker build --build-arg DISTRO=14.04 MATRIX='echo Ok!' -t trusty_tahr ./misc"
    #     - TESTS="docker run -it misc_trusty_tahr_1 bash -c 'cd /code/gamera && py.test'"
    # Mac Installation.
    - os: osx
      osx_image: xcode9.4
      env:
        - HOMEBREW_NO_AUTO_UPDATE=1
        - MATRIX="brew install python@2 wxpython && pip install -U pip && export PATH=$PATH:/Users/travis/Library/Python/2.7/bin"
        - TESTS="py.test"
    - os: osx
      osx_image: xcode9.3
      env:
        - HOMEBREW_NO_AUTO_UPDATE=1
        - MATRIX="brew link --overwrite python && brew install python@2 wxpython && sudo -H pip install -U pip"
        - TESTS="py.test"
install:
  - eval ${MATRIX}
  - pip install --user pytest docutils pygments
  - python setup.py build
  - python setup.py install
script:
  - eval ${TESTS}
