language: generic
sudo: required
matrix:
  include:
    # Linux Installation.
    - os: linux
      env:
        - MATRIX_EVAL="sudo apt-get install python-wxgtk3.0 python-pip && pip install wxpython==2.8.11.0"
    - os: linux
      env:
        - MATRIX_EVAL="sudo apt-get install python-wxgtk3.0 python-pip && pip install wxpython==2.8.11.0"
    # Mac Installation.
    - os: osx
      osx_image: xcode9.4
      env:
        - MATRIX_EVAL="HOMEBREW_NO_AUTO_UPDATE=1 brew install python@2 wxpython"
    - os: osx
      osx_image: xcode9.3
      env:
        - MATRIX_EVAL="HOMEBREW_NO_AUTO_UPDATE=1 brew install python@2 wxpython"
    - os: osx
      osx_image: xcode9.2
      env:
        - MATRIX_EVAL="HOMEBREW_NO_AUTO_UPDATE=1 brew install python@2 wxpython"
    - os: osx
      osx_image: xcode9.1
      env:
        - MATRIX_EVAL="HOMEBREW_NO_AUTO_UPDATE=1 brew install python@2 wxpython"
    - os: osx
      osx_image: xcode9
      env:
        - MATRIX_EVAL="HOMEBREW_NO_AUTO_UPDATE=1 brew install python@2 wxpython"
    - os: osx
      osx_image: xcode8.3
      env:
        - MATRIX_EVAL="HOMEBREW_NO_AUTO_UPDATE=1 brew install python@2 wxpython"
    - os: osx
      osx_image: xcode8
      env:
        - MATRIX_EVAL="HOMEBREW_NO_AUTO_UPDATE=1 brew install python@2 wxpython"
before_install:
  - eval "${MATRIX_EVAL}"
  - pip install pytest
install:
  - python setup.py build
  - python setup.py install
script:
  - py.test
